# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b25e3484b6a2708384d77e385b38359abbf42dfd6d0ff441f4b2199686489b301bf4b8caa12bd942990b024636783d542ee6f9b39d1bc457ff6b34aeb4bde26

test:
  secret_key_base: 68f953afb31f32442c23184bc2218f96a753cdf6c2191ca9e46bec19ef2e727f57ae16dd353104339bbec74d9efe89925886305ae489ed55075a0bca8b449a8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
